### ISSUE TITLE
Conflict between machinectl login and container

### ISSUE THREAD

**Issue by Louson** [bjc/tramp-nspawn#3]
When I log on /nspawn:buildname: it asks for a user/password. At that stage, if I enter my container credentials, my log is rejected.
If I enter my host credentials, I am logged as root.

I guess the problem is that I need credentials to talk with machined over dbus.

**Comment by bjc** [comment]
By default, `machinectl` uses root as the target user on the container, so `tramp-nspawn` does the same thing. If you want to use a specific user you have to use the `user@machine` syntax: `/nspawn:louson@container:/the/remote/file`.

**Comment by Louson** [comment]
oh ! indeed. I was confused because the password is still the host one
